---
- hosts: web
  remote_user: ubuntu
  become: yes
  vars_prompt:
    - name: password
      prompt: "Please enter password"
      private: yes

  vars:
    - dir_name: test
    - myname: omar

  tasks:
  