---
- hosts: web
  remote_user: ubuntu
  become: yes
  vars_prompt:
    - name: password
      prompt: "Please enter password"
      private: yes

  vars:
    - dir_name: test

  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present

    - name: create dir
      file:
        path: "{{ dir_name }}"
        state: directory

    - name: list
      command: "ls {{ dir_name }}"
      register: result

    - name: print stdout
      debug:
        var: result.stdout
